# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NtM443Gmpvkk4E7A6fCydhvcfT11jfM
"""

import streamlit as st
import pandas as pd
import pickle
import statsmodels.api as sm

# ----------------- LOAD PICKLE -----------------
with open("model_with_clusters.pkl", "rb") as f:
    artifacts = pickle.load(f)

clf_model = artifacts["classification_model"]
class_feature_names = artifacts["class_feature_names"]

cluster_model = artifacts["cluster_model"]
cluster_summary = artifacts["cluster_summary"]

# infer cluster label column name (e.g. 'cluster_label')
cluster_label_col = cluster_summary.columns[0]  # first column is the cluster id

# ----------------- STREAMLIT UI -----------------
st.title("📊 Response Prediction & Cluster Highlight Dashboard")

st.write(
    """
    This app:
    - Predicts **Yes/No response** for a record
    - Assigns it to a **cluster**
    - Shows how that cluster behaves in terms of **Yes/No rate**
    """
)

st.subheader("Model Inputs")

# We assume there are exactly 2 numeric features in class_feature_names
feat1_name = class_feature_names[0]
feat2_name = class_feature_names[1]

feat1_value = st.number_input(f"{feat1_name}", value=0.0)
feat2_value = st.number_input(f"{feat2_name}", value=0.0)

if st.button("Predict & Show Cluster Insights"):
    # ------------- PREPARE INPUT FOR CLASSIFICATION -------------
    input_df = pd.DataFrame([[feat1_value, feat2_value]],
                            columns=class_feature_names)

    # add constant term for statsmodels
    input_df_const = sm.add_constant(input_df, has_constant="add")

    # predicted probability of response = 1 (Yes)
    prob_yes = float(clf_model.predict(input_df_const)[0])
    pred_label = 1 if prob_yes >= 0.5 else 0

    # ------------- PREPARE INPUT FOR CLUSTERING -------------
    # here we assume clustering was done on the same two features
    cluster_input = input_df.values  # shape (1, 2)
    cluster_id = int(cluster_model.predict(cluster_input)[0])

    # get this cluster's summary row
    row = cluster_summary[cluster_summary[cluster_label_col] == cluster_id]

    if row.empty:
        st.warning("Cluster not found in summary table.")
    else:
        row = row.iloc[0]
        cluster_size = int(row["count"])
        yes_rate = float(row["response_yes_rate"])  # 0–1

        # ------------- SHOW PREDICTION -------------
        st.subheader("Prediction Result")

        if pred_label == 1:
            st.success(
                f"✅ **Predicted Response: YES**  \n"
                f"Estimated probability of YES: `{prob_yes:.2f}`"
            )
        else:
            st.error(
                f"❌ **Predicted Response: NO**  \n"
                f"Estimated probability of YES: `{prob_yes:.2f}`"
            )

        # ------------- SHOW CLUSTER INFO & HIGHLIGHT -------------
        st.subheader("Cluster Behaviour")

        st.write(f"You fall into **Cluster {cluster_id}**.")

        # Color logic based on Yes rate
        if yes_rate >= 0.7:
            st.success(
                f"🟢 This is a **YES-dominant cluster** "
                f"(Yes rate: `{yes_rate:.2f}`, Records: `{cluster_size}`)"
            )
        elif yes_rate <= 0.3:
            st.error(
                f"🔴 This is a **NO-dominant cluster** "
                f"(Yes rate: `{yes_rate:.2f}`, Records: `{cluster_size}`)"
            )
        else:
            st.warning(
                f"🟡 This cluster is **mixed** "
                f"(Yes rate: `{yes_rate:.2f}`, Records: `{cluster_size}`)"
            )

        # Show full cluster summary table below
        with st.expander("See full cluster-wise Yes/No behaviour"):
            st.dataframe(cluster_summary)